# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, QObject
from db import TodoDatabase


class Ui_Dialog(QObject):

    def __init__(self):
        super().__init__()
        self.editItemWindow = None
        self.isEditItemOpen = False
        self.tempItems = []

        db =  TodoDatabase()
        db.create_database()
        self.tempItems = db.fetch()


    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(591, 514)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 551, 471))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 8, -1, 8)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addItem = QtWidgets.QPushButton(self.verticalLayoutWidget, clicked=lambda: self.add_it())
        self.addItem.setMinimumSize(QtCore.QSize(0, 30))
        self.addItem.setBaseSize(QtCore.QSize(0, 0))
        self.addItem.setObjectName("addItem")
        self.horizontalLayout.addWidget(self.addItem)
        self.editItem = QtWidgets.QPushButton(self.verticalLayoutWidget, clicked=lambda: self.edit_it())
        self.editItem.setMinimumSize(QtCore.QSize(0, 30))
        self.editItem.setObjectName("editItem")
        self.horizontalLayout.addWidget(self.editItem)
        self.removeItem = QtWidgets.QPushButton(self.verticalLayoutWidget, clicked=lambda: self.remove_it())
        self.removeItem.setMinimumSize(QtCore.QSize(0, 30))
        self.removeItem.setBaseSize(QtCore.QSize(0, 0))
        self.removeItem.setObjectName("removeItem")
        self.horizontalLayout.addWidget(self.removeItem)
        self.clearList = QtWidgets.QPushButton(self.verticalLayoutWidget, clicked=lambda: self.clear_list())
        self.clearList.setMinimumSize(QtCore.QSize(0, 30))
        self.clearList.setBaseSize(QtCore.QSize(0, 0))
        self.clearList.setObjectName("clearList")
        self.horizontalLayout.addWidget(self.clearList)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)

        for item in self.tempItems:
            self.add_it_from_db(item[0])

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def add_it_from_db(self, item):
        self.listWidget.addItem(item)

    def add_it(self):
        if self.lineEdit.text() != "":
            item = self.lineEdit.text()
            self.listWidget.addItem(item)
            self.lineEdit.setText("")

    def edit_it(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_EditItem()
        self.ui.setupUi(self.window)

        print(self.isEditItemOpen)

        if self.isEditItemOpen == False:
            if self.listWidget.currentItem():
                self.isEditItemOpen = True
                thing = self.listWidget.currentItem().text()
                self.ui.editLineItem.setText(thing)
                self.ui.submitClickedAccept.connect(self.change_item)
                self.ui.submitClickedCancel.connect(self.cancle_change)
                self.window.show()

    def change_item(self, data):
        self.listWidget.currentItem().setText(data)
        self.isEditItemOpen = False
    
    def cancle_change(self):
        self.isEditItemOpen = False


    def remove_it(self):
        active = self.listWidget.currentRow()
        self.listWidget.takeItem(active)

    def clear_list(self):
        self.listWidget.clear()


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Todo List"))
        self.addItem.setText(_translate("Dialog", "Add Item"))
        self.editItem.setText(_translate("Dialog", "Edit Item"))
        self.removeItem.setText(_translate("Dialog", "Remove Item"))
        self.clearList.setText(_translate("Dialog", "Clear List"))



class Ui_EditItem(QObject):
    submitClickedAccept = QtCore.pyqtSignal(str)
    submitClickedCancel = QtCore.pyqtSignal()

    def __init__(self):
        super().__init__()

    def setupUi(self, EditItem):
        EditItem.setObjectName("EditItem")
        EditItem.resize(348, 120)
        self.buttonBox = QtWidgets.QDialogButtonBox(EditItem)
        self.buttonBox.setGeometry(QtCore.QRect(100, 70, 156, 41))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox(clicked=lambda: self.exit()).Cancel|QtWidgets.QDialogButtonBox(clicked=lambda: self.accept()).Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.editLineItem = QtWidgets.QLineEdit(EditItem)
        self.editLineItem.setGeometry(QtCore.QRect(20, 30, 311, 31))
        self.editLineItem.setObjectName("editLineItem")
        
        self.buttonBox.accepted.connect(lambda: self.accept(EditItem))
        self.buttonBox.rejected.connect(lambda: self.exit(EditItem))

        self.retranslateUi(EditItem)
        QtCore.QMetaObject.connectSlotsByName(EditItem)

    def exit(self, EditItem):
        self.submitClickedCancel.emit()
        EditItem.close()

    def accept(self, EditItem):
        self.submitClickedAccept.emit(self.editLineItem.text())
        self.editLineItem.setText("")
        EditItem.close()

    def retranslateUi(self, EditItem):
        _translate = QtCore.QCoreApplication.translate
        EditItem.setWindowTitle(_translate("EditItem", "Edit Item"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()

    # EditItem = QtWidgets.QWidget()
    # ui = Ui_EditItem()
    # ui.setupUi(EditItem)

    sys.exit(app.exec_())
